package com.kun.flow.data;

import com.kun.flow.model.TestFun;
import com.kun.flow.model.TestFunExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestFunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTFORFUN
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    int countByExample(TestFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTFORFUN
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    int deleteByExample(TestFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTFORFUN
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    int insert(TestFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTFORFUN
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    int insertSelective(TestFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTFORFUN
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    List<TestFun> selectByExample(TestFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTFORFUN
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") TestFun record, @Param("example") TestFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTFORFUN
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    int updateByExample(@Param("record") TestFun record, @Param("example") TestFunExample example);
}