package com.kun.flow.model;

public class TestFun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTFORFUN.ID
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTFORFUN.NAME
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTFORFUN.NICKNAME
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTFORFUN.PHONENUMBER
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    private Short phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTFORFUN.EMAIL
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTFORFUN.ID
     *
     * @return the value of TESTFORFUN.ID
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTFORFUN.ID
     *
     * @param id the value for TESTFORFUN.ID
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTFORFUN.NAME
     *
     * @return the value of TESTFORFUN.NAME
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTFORFUN.NAME
     *
     * @param name the value for TESTFORFUN.NAME
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTFORFUN.NICKNAME
     *
     * @return the value of TESTFORFUN.NICKNAME
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTFORFUN.NICKNAME
     *
     * @param nickname the value for TESTFORFUN.NICKNAME
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTFORFUN.PHONENUMBER
     *
     * @return the value of TESTFORFUN.PHONENUMBER
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public Short getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTFORFUN.PHONENUMBER
     *
     * @param phonenumber the value for TESTFORFUN.PHONENUMBER
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public void setPhonenumber(Short phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTFORFUN.EMAIL
     *
     * @return the value of TESTFORFUN.EMAIL
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTFORFUN.EMAIL
     *
     * @param email the value for TESTFORFUN.EMAIL
     *
     * @mbggenerated Tue Nov 11 22:40:58 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}